version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
       sh -c "cd /user/home &&
              source venv/bin/activate &&
              cd mazerunner/ && 
              python manage.py runserver 0.0.0.0:8000"